---

- name: disable ipv6 'conf.all'
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^net.ipv6.conf.all.disable_ipv6 = .*"
    line: "net.ipv6.conf.all.disable_ipv6 = 1"
    state: present
  become: true

- name: disable ipv6 'conf.default'
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^net.ipv6.conf.default.disable_ipv6 = .*"
    line: "net.ipv6.conf.default.disable_ipv6 = 1"
    state: present
  become: true

- name: disable ipv6 'conf.lo'
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^net.ipv6.conf.lo.disable_ipv6 = .*"
    line: "net.ipv6.conf.lo.disable_ipv6 = 1"
    state: present
  become: true

- name: check if ipv6 is indeed disabled
  shell: 'cat /proc/sys/net/ipv6/conf/all/disable_ipv6'
  register: _ipv6_disabled
  changed_when: False

- debug:
    msg: "ipv6 disabled: {{ _ipv6_disabled.stdout }}"

- name: enforce ipv6 disabling
  command: 'sysctl -p'
  become: true
  when: _ipv6_disabled.stdout != "1"

- name: check again if ipv6 is disabled
  shell: 'cat /proc/sys/net/ipv6/conf/all/disable_ipv6'
  register: _ipv6_disabled2
  when: _ipv6_disabled.stdout != "1"
  changed_when: False

- fail:
    msg: "Failed to disable ipv6."
  when: _ipv6_disabled.stdout != "1" and _ipv6_disabled2.stdout != "1"
